In [ ]:
#Import Necessary Library
import pandas as pd

In [ ]:
#Load Dataset
df=pd.read_excel('/content/_Data Sets Reward_Program_Assignment_Input_v6 - TA.xlsx', sheet_name ='Mentorship_Sessions')
# Display initial data
df.head()

,Unnamed: 0,Mentor_ID,Mentor_Name,Mentee_Name,Session_Number,Session_Duration_Min,Job_Info_Completed,Session_Date,Points_Awarded
0,2001.0,1003.0,Sarah Clark,Bob Brown,1.0,40.0,Yes,2023-01-01,NaN
1,2002.0,1003.0,Emily Davis,Carol White,2.0,30.0,Yes,2023-01-08,NaN
2,2003.0,1005.0,James Wilson,Jane Smith,2.0,40.0,Yes,2023-01-15,NaN
3,4.0,1005.0,David Thompson,NaN,2.0,50.0,Yes,2023-01-22,NaN
4,2001.0,1004.0,Emily Davis,Bob Brown,1.0,30.0,No,2023-01-29,NaN

In [ ]:
# Check data types
df.dtypes

Unnamed: 0              float64
Mentor_ID               float64
Mentor_Name              object
Mentee_Name              object
Session_Number          float64
Session_Duration_Min    float64
Job_Info_Completed       object
Session_Date             object
Points_Awarded          float64
dtype: object

In [ ]:
#Check missing values
df.isnull().sum()

Unnamed: 0                1
Mentor_ID                 1
Mentor_Name               0
Mentee_Name               2
Session_Number            1
Session_Duration_Min      2
Job_Info_Completed        1
Session_Date              1
Points_Awarded          109
dtype: int64

In [ ]:
# Drop unwanted columns but keep others
df = df.drop(['Points_Awarded'], axis=1)

In [ ]:
# Drop the first column since it's not needed
df= df.drop(df.columns[0], axis=1)

In [ ]:
# Remove rows with NaN values
df = df.dropna()

In [ ]:
#Confirm there is no nulls
df.isnull().sum()

Mentor_ID               0
Mentor_Name             0
Mentee_Name             0
Session_Number          0
Session_Duration_Min    0
Job_Info_Completed      0
Session_Date            0
dtype: int64

In [ ]:
#Check the number of duplicates
df.duplicated().sum()

2

In [ ]:
#Drop duplicates
df.drop_duplicates(inplace=True)

In [ ]:
# Filter out specific rows based on conditions
df = df[df['Job_Info_Completed'] != 'Maybe']

In [ ]:
#Have a look at the dataset once more
df

,Mentor_ID,Mentor_Name,Mentee_Name,Session_Number,Session_Duration_Min,Job_Info_Completed,Session_Date
0,1003.0,Sarah Clark,Bob Brown,1.0,40.0,Yes,2023-01-01
1,1003.0,Emily Davis,Carol White,2.0,30.0,Yes,2023-01-08
2,1005.0,James Wilson,Jane Smith,2.0,40.0,Yes,2023-01-15
4,1004.0,Emily Davis,Bob Brown,1.0,30.0,No,2023-01-29
5,1002.0,David Thompson,Jane Smith,2.0,50.0,No,2023-02-05
...,...,...,...,...,...,...,...
102,1003.0,Michael Lee,Bob Brown,1.0,20.0,Yes,2024-11-17
103,1001.0,Michael Lee,Alice Johnson,2.0,20.0,Yes,2024-11-24
104,1003.0,Michael Lee,Carol White,2.0,20.0,No,2024-08-04
106,1005.0,Michael Lee,Jane Smith,1.0,50.0,Yes,2024-05-05
108,1004.0,Michael Lee,Jane Smith,1.0,30.0,No,2023-11-05

In [ ]:
#Change the data types of these 3 columns
df['Mentor_ID'] = df['Mentor_ID'].astype(int)
df['Session_Number'] = df['Session_Number'].astype(int)
df['Session_Duration_Min'] = df['Session_Duration_Min'].astype(int)

In [ ]:
#Save Cleaned Data to an excel file
df.to_excel('clean_data.xlsx', index=False)